logo: false
paginate: 20
domain_name: 'http://binnng.github.io'
baseurl: "/i" # the subpath of your site, e.g. /blog/
# Details for the RSS feed generator
url: "http://binnng.github.io/i/" # the base hostname & protocol for your site
author:         'binnng'
name:          '老婆婆的远大梦想'
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'config.ru', 'unicorn.rb', 'Procfile']