// Generated by CoffeeScript 1.9.2
var fs, getName, instead, postFolder, start;

fs = require("fs");

postFolder = "../_posts";

getName = function(url) {
  var match;
  match = url.match(/images\/(.*?)(.jpg|.png)/);
  return match[1];
};

instead = function(cnt, match) {
  var img, newCnt, reg;
  img = getName(match);
  reg = new RegExp("[^\\n]*" + match + "[^\\n]*\\n?", "g");
  newCnt = cnt.replace(reg, "");
  newCnt = newCnt.replace("layout: post", "layout: post\nimage: " + img);
  return newCnt;
};

start = function() {
  return fs.readdir(postFolder, function(err, files) {
    return files.forEach(function(file, idx) {
      return fs.readFile(postFolder + "/" + file, "utf-8", function(err, cnt) {
        var match;
        match = cnt.match(/images\/(.*?)(.jpg|.png)/g);
        if (match && match[0]) {
          return fs.writeFileSync(postFolder + "/" + file, instead(cnt, match[0]), "utf-8", function() {});
        }
      });
    });
  });
};

start();
